package-source/1GP/objects/Custom_Object__c/Custom_Object__c.object-meta.xml
<CustomObject>
    <description>A simple custom object to test the intersection of Apex class versions and custom object</description>
    <label>Custom Object</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package-source/2GP/core-app/objects/Custom_Object__c/fields/Custom_Field_1__c.field-meta.xml
<CustomField>
    <fullName>Custom_Field_1__c</fullName>
    <description>Custom field that was added in ver 3.0 of the package with a length of 100.</description>
    <inlineHelpText>Custom field that was added in ver 3.0 of the package with a length of 100.</inlineHelpText>
    <label>Custom Field 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

package-source/1GP/classes/ConcreteClassTwo.cls
// Appears in ver 3.0
public class ConcreteClassTwo {
    
    // Appears in ver 3.0 - returns 'customObjects-->' + customObjects
    public String methodOne(Boolean arg1) {
        List<Custom_Object__c> customObjects = [SELECT ID, Name, Custom_Field_1__c FROM Custom_Object__c];
        String retVal = 'customObjects-->' + customObjects;
        System.Debug(retVal);
        return retVal;
    }

    // Appears in ver 3.0 - returns void
    public void methodTwo() {
        System.debug('Concrete implementation of methodThree');
    }
    
}